
# application will use this file when you set profile active as uat in main YML file (application.yml)

server:
  port: 8082

message:
  title: Hello from UAT (YML File)
  description: This is from UAT environment (YML File)